[CustomMessages]
InstallingService=Installing service...
UninstallingService=Uninstalling service...
StartingService=Starting service...
StoppingService=Stopping service...
BackingUpState=Backing up settings...
CreateDebugShortcut=Create a Debug &shortcut in the Start Menu
CreateProgramDirShortcut=Create a shortcut to the Data directory in the Start &Menu
ConfiguringFirewall=Configuring Windows firewall...
